name: mb
channels:
  - defaults
dependencies:
  - python=3.8.20
  - pip:
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.8
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorama==0.4.6
      - contourpy==1.1.1
      - cycler==0.12.1
      - cython==3.0.12
      - docker-pycreds==0.4.0
      - eval-type-backport==0.2.2
      # - fairseq==1.0.0a0+3369427 # replace all np.float with float
      - filelock==3.16.1
      - fonttools==4.56.0
      - fsspec==2025.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - huggingface-hub==0.29.3
      - hydra-core==1.0.0
      - idna==3.10
      - importlib-resources==6.4.5
      - jinja2==3.1.5
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - lxml==5.3.1
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - miditoolkit==1.0.1
      - mido==1.3.3
      - mpmath==1.3.0
      - networkx==3.1
      - numpy==1.24.4
      - omegaconf==2.1.2 # omegaconf==2.1.1
      - packaging==24.2
      - pandas==2.0.3
      - pillow==10.4.0
      - platformdirs==4.3.6
      - portalocker==3.0.0
      - pretty-midi==0.2.10
      - protobuf==5.29.3
      - psutil==7.0.0
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - sacrebleu==2.5.1
      - safetensors==0.5.3
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - sentry-sdk==2.22.0
      - setproctitle==1.3.5
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.13.3
      - tabulate==0.9.0
      - threadpoolctl==3.5.0
      - tokenizers==0.20.3
      - torch==2.4.1
      - tqdm==4.67.1
      - transformers==4.46.3
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - urllib3==2.2.3
      - wandb==0.19.8
      - zipp==3.20.2
      - gdown

